=begin
#The Selling Partner API for Finances

#The Selling Partner API for Finances provides financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.

OpenAPI spec version: 2024-06-19

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/finances-api-model-20240619/api_client'
require 'amz_sp_api/finances-api-model-20240619/api_error'
require 'amz_sp_api/finances-api-model-20240619/version'
require 'amz_sp_api/finances-api-model-20240619/configuration'

# Models
require 'amz_sp_api/finances-api-model-20240619/models/amazon_pay_context'
require 'amz_sp_api/finances-api-model-20240619/models/big_decimal'
require 'amz_sp_api/finances-api-model-20240619/models/breakdown'
require 'amz_sp_api/finances-api-model-20240619/models/breakdowns'
require 'amz_sp_api/finances-api-model-20240619/models/business_context'
require 'amz_sp_api/finances-api-model-20240619/models/context'
require 'amz_sp_api/finances-api-model-20240619/models/contexts'
require 'amz_sp_api/finances-api-model-20240619/models/currency'
require 'amz_sp_api/finances-api-model-20240619/models/date'
require 'amz_sp_api/finances-api-model-20240619/models/deferred_context'
require 'amz_sp_api/finances-api-model-20240619/models/error'
require 'amz_sp_api/finances-api-model-20240619/models/error_list'
require 'amz_sp_api/finances-api-model-20240619/models/item'
require 'amz_sp_api/finances-api-model-20240619/models/item_related_identifier'
require 'amz_sp_api/finances-api-model-20240619/models/item_related_identifiers'
require 'amz_sp_api/finances-api-model-20240619/models/items'
require 'amz_sp_api/finances-api-model-20240619/models/list_transactions_response'
require 'amz_sp_api/finances-api-model-20240619/models/marketplace_details'
require 'amz_sp_api/finances-api-model-20240619/models/payments_context'
require 'amz_sp_api/finances-api-model-20240619/models/product_context'
require 'amz_sp_api/finances-api-model-20240619/models/related_identifier'
require 'amz_sp_api/finances-api-model-20240619/models/related_identifiers'
require 'amz_sp_api/finances-api-model-20240619/models/selling_partner_metadata'
require 'amz_sp_api/finances-api-model-20240619/models/time_range_context'
require 'amz_sp_api/finances-api-model-20240619/models/transaction'
require 'amz_sp_api/finances-api-model-20240619/models/transactions'
require 'amz_sp_api/finances-api-model-20240619/models/transactions_payload'

# APIs
require 'amz_sp_api/finances-api-model-20240619/api/default_api'

module AmzSpApi::FinancesApiModel
  class AmzSpApi::FinancesApiModel::V20240619::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::FinancesApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
