=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::ExternalFulfillment
  # Information about a line item in a shipment.
  class AmzSpApi::ExternalFulfillment::V20240911::ShipmentLineItem
    # An identifier for a shipment's line item. This identifier is guaranteed to be unique within the scope of its containing shipment.
    attr_accessor :shipment_line_item_id

    attr_accessor :merchant_sku

    # The number of items of the SKU in this line item.
    attr_accessor :number_of_units

    # The serial numbers for each item in this line item.
    attr_accessor :serial_numbers

    attr_accessor :piece_type

    # A list of HAZMAT label identifiers that must be applied to the packages for this line item.
    attr_accessor :hazmat_labels

    attr_accessor :gift_attributes

    attr_accessor :charges

    attr_accessor :cancellations

    # The HSN code of SKU in this line item.
    attr_accessor :hsn_code

    attr_accessor :recommended_country_of_origin

    attr_accessor :country_of_origin

    # The three digit currency code of the currency recommended by the marketplace, in ISO 4217 format.
    attr_accessor :recommended_currency_code

    attr_accessor :item_value

    attr_accessor :compliance_attributes

    # A list of custom passthrough attributes. For details on these attributes, reach out to your respective program teams at Amazon.
    attr_accessor :custom_attributes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'shipment_line_item_id' => :'shipmentLineItemId',
        :'merchant_sku' => :'merchantSku',
        :'number_of_units' => :'numberOfUnits',
        :'serial_numbers' => :'serialNumbers',
        :'piece_type' => :'pieceType',
        :'hazmat_labels' => :'hazmatLabels',
        :'gift_attributes' => :'giftAttributes',
        :'charges' => :'charges',
        :'cancellations' => :'cancellations',
        :'hsn_code' => :'hsnCode',
        :'recommended_country_of_origin' => :'recommendedCountryOfOrigin',
        :'country_of_origin' => :'countryOfOrigin',
        :'recommended_currency_code' => :'recommendedCurrencyCode',
        :'item_value' => :'itemValue',
        :'compliance_attributes' => :'complianceAttributes',
        :'custom_attributes' => :'customAttributes'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'shipment_line_item_id' => :'Object',
        :'merchant_sku' => :'Object',
        :'number_of_units' => :'Object',
        :'serial_numbers' => :'Object',
        :'piece_type' => :'Object',
        :'hazmat_labels' => :'Object',
        :'gift_attributes' => :'Object',
        :'charges' => :'Object',
        :'cancellations' => :'Object',
        :'hsn_code' => :'Object',
        :'recommended_country_of_origin' => :'Object',
        :'country_of_origin' => :'Object',
        :'recommended_currency_code' => :'Object',
        :'item_value' => :'Object',
        :'compliance_attributes' => :'Object',
        :'custom_attributes' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AmzSpApi::ExternalFulfillment::ShipmentLineItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AmzSpApi::ExternalFulfillment::ShipmentLineItem`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'shipment_line_item_id')
        self.shipment_line_item_id = attributes[:'shipment_line_item_id']
      end

      if attributes.key?(:'merchant_sku')
        self.merchant_sku = attributes[:'merchant_sku']
      end

      if attributes.key?(:'number_of_units')
        self.number_of_units = attributes[:'number_of_units']
      end

      if attributes.key?(:'serial_numbers')
        if (value = attributes[:'serial_numbers']).is_a?(Array)
          self.serial_numbers = value
        end
      end

      if attributes.key?(:'piece_type')
        self.piece_type = attributes[:'piece_type']
      end

      if attributes.key?(:'hazmat_labels')
        if (value = attributes[:'hazmat_labels']).is_a?(Array)
          self.hazmat_labels = value
        end
      end

      if attributes.key?(:'gift_attributes')
        self.gift_attributes = attributes[:'gift_attributes']
      end

      if attributes.key?(:'charges')
        self.charges = attributes[:'charges']
      end

      if attributes.key?(:'cancellations')
        self.cancellations = attributes[:'cancellations']
      end

      if attributes.key?(:'hsn_code')
        self.hsn_code = attributes[:'hsn_code']
      end

      if attributes.key?(:'recommended_country_of_origin')
        self.recommended_country_of_origin = attributes[:'recommended_country_of_origin']
      end

      if attributes.key?(:'country_of_origin')
        self.country_of_origin = attributes[:'country_of_origin']
      end

      if attributes.key?(:'recommended_currency_code')
        self.recommended_currency_code = attributes[:'recommended_currency_code']
      end

      if attributes.key?(:'item_value')
        self.item_value = attributes[:'item_value']
      end

      if attributes.key?(:'compliance_attributes')
        self.compliance_attributes = attributes[:'compliance_attributes']
      end

      if attributes.key?(:'custom_attributes')
        if (value = attributes[:'custom_attributes']).is_a?(Array)
          self.custom_attributes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @shipment_line_item_id.nil?
        invalid_properties.push('invalid value for "shipment_line_item_id", shipment_line_item_id cannot be nil.')
      end

      if @merchant_sku.nil?
        invalid_properties.push('invalid value for "merchant_sku", merchant_sku cannot be nil.')
      end

      if @number_of_units.nil?
        invalid_properties.push('invalid value for "number_of_units", number_of_units cannot be nil.')
      end

      if @charges.nil?
        invalid_properties.push('invalid value for "charges", charges cannot be nil.')
      end

      if @compliance_attributes.nil?
        invalid_properties.push('invalid value for "compliance_attributes", compliance_attributes cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @shipment_line_item_id.nil?
      return false if @merchant_sku.nil?
      return false if @number_of_units.nil?
      return false if @charges.nil?
      return false if @compliance_attributes.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class AmzSpApi::ExternalFulfillment::V20240911::== o.class AmzSpApi::ExternalFulfillment::V20240911::&&
          shipment_line_item_id == o.shipment_line_item_id &&
          merchant_sku == o.merchant_sku &&
          number_of_units == o.number_of_units &&
          serial_numbers == o.serial_numbers &&
          piece_type == o.piece_type &&
          hazmat_labels == o.hazmat_labels &&
          gift_attributes == o.gift_attributes &&
          charges == o.charges &&
          cancellations == o.cancellations &&
          hsn_code == o.hsn_code &&
          recommended_country_of_origin == o.recommended_country_of_origin &&
          country_of_origin == o.country_of_origin &&
          recommended_currency_code == o.recommended_currency_code &&
          item_value == o.item_value &&
          compliance_attributes == o.compliance_attributes &&
          custom_attributes == o.custom_attributes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [shipment_line_item_id, merchant_sku, number_of_units, serial_numbers, piece_type, hazmat_labels, gift_attributes, charges, cancellations, hsn_code, recommended_country_of_origin, country_of_origin, recommended_currency_code, item_value, compliance_attributes, custom_attributes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmzSpApi::ExternalFulfillment.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
