=begin
#Selling Partner API for Delivery Shipment Invoicing

#The Selling Partner API for Delivery Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s orders.

OpenAPI spec version: 2022-07-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::DeliveryByAmazon
  class InvoiceType
    OUTBOUND = 'Outbound'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = InvoiceType.constants.select { |c| InvoiceType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #InvoiceType" if constantValues.empty?
      value
    end
  end
end
