=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/external-fulfillment-20240911/api_client'
require 'amz_sp_api/external-fulfillment-20240911/api_error'
require 'amz_sp_api/external-fulfillment-20240911/version'
require 'amz_sp_api/external-fulfillment-20240911/configuration'

# Models
require 'amz_sp_api/external-fulfillment-20240911/models/address'
require 'amz_sp_api/external-fulfillment-20240911/models/amount'
require 'amz_sp_api/external-fulfillment-20240911/models/cancellation'
require 'amz_sp_api/external-fulfillment-20240911/models/cancellations'
require 'amz_sp_api/external-fulfillment-20240911/models/charge'
require 'amz_sp_api/external-fulfillment-20240911/models/charge_breakup'
require 'amz_sp_api/external-fulfillment-20240911/models/charges'
require 'amz_sp_api/external-fulfillment-20240911/models/compliance_attributes'
require 'amz_sp_api/external-fulfillment-20240911/models/country_code'
require 'amz_sp_api/external-fulfillment-20240911/models/courier_supported_attributes'
require 'amz_sp_api/external-fulfillment-20240911/models/custom_attribute'
require 'amz_sp_api/external-fulfillment-20240911/models/custom_attribute_type'
require 'amz_sp_api/external-fulfillment-20240911/models/custom_channel_attribute'
require 'amz_sp_api/external-fulfillment-20240911/models/date_time'
require 'amz_sp_api/external-fulfillment-20240911/models/decimal'
require 'amz_sp_api/external-fulfillment-20240911/models/dimension'
require 'amz_sp_api/external-fulfillment-20240911/models/document'
require 'amz_sp_api/external-fulfillment-20240911/models/document_v2'
require 'amz_sp_api/external-fulfillment-20240911/models/error'
require 'amz_sp_api/external-fulfillment-20240911/models/error_list'
require 'amz_sp_api/external-fulfillment-20240911/models/gift_attributes'
require 'amz_sp_api/external-fulfillment-20240911/models/invoice_info'
require 'amz_sp_api/external-fulfillment-20240911/models/invoice_requirement'
require 'amz_sp_api/external-fulfillment-20240911/models/invoice_response'
require 'amz_sp_api/external-fulfillment-20240911/models/line_item'
require 'amz_sp_api/external-fulfillment-20240911/models/line_item_with_reason'
require 'amz_sp_api/external-fulfillment-20240911/models/marketplace_attributes'
require 'amz_sp_api/external-fulfillment-20240911/models/original_line_item'
require 'amz_sp_api/external-fulfillment-20240911/models/original_line_items'
require 'amz_sp_api/external-fulfillment-20240911/models/package'
require 'amz_sp_api/external-fulfillment-20240911/models/package_delivery_status'
require 'amz_sp_api/external-fulfillment-20240911/models/package_dimensions'
require 'amz_sp_api/external-fulfillment-20240911/models/package_line_item'
require 'amz_sp_api/external-fulfillment-20240911/models/package_line_items'
require 'amz_sp_api/external-fulfillment-20240911/models/package_ship_label'
require 'amz_sp_api/external-fulfillment-20240911/models/package_ship_label_list'
require 'amz_sp_api/external-fulfillment-20240911/models/package_status'
require 'amz_sp_api/external-fulfillment-20240911/models/package_sub_status'
require 'amz_sp_api/external-fulfillment-20240911/models/packages'
require 'amz_sp_api/external-fulfillment-20240911/models/packing_slip_requirement'
require 'amz_sp_api/external-fulfillment-20240911/models/pagination'
require 'amz_sp_api/external-fulfillment-20240911/models/party_identification_info'
require 'amz_sp_api/external-fulfillment-20240911/models/party_identification_info_list'
require 'amz_sp_api/external-fulfillment-20240911/models/piece_type'
require 'amz_sp_api/external-fulfillment-20240911/models/presence_status'
require 'amz_sp_api/external-fulfillment-20240911/models/priority'
require 'amz_sp_api/external-fulfillment-20240911/models/recommended_package'
require 'amz_sp_api/external-fulfillment-20240911/models/recommended_package_line_item'
require 'amz_sp_api/external-fulfillment-20240911/models/recommended_package_line_items'
require 'amz_sp_api/external-fulfillment-20240911/models/recommended_packages'
require 'amz_sp_api/external-fulfillment-20240911/models/replaced_shipment_info'
require 'amz_sp_api/external-fulfillment-20240911/models/requirement_level'
require 'amz_sp_api/external-fulfillment-20240911/models/sku'
require 'amz_sp_api/external-fulfillment-20240911/models/serial_number'
require 'amz_sp_api/external-fulfillment-20240911/models/ship_label_metadata'
require 'amz_sp_api/external-fulfillment-20240911/models/ship_labels_input'
require 'amz_sp_api/external-fulfillment-20240911/models/ship_labels_response'
require 'amz_sp_api/external-fulfillment-20240911/models/shipment'
require 'amz_sp_api/external-fulfillment-20240911/models/shipment_acknowledgement_request'
require 'amz_sp_api/external-fulfillment-20240911/models/shipment_info'
require 'amz_sp_api/external-fulfillment-20240911/models/shipment_line_item'
require 'amz_sp_api/external-fulfillment-20240911/models/shipment_requirements'
require 'amz_sp_api/external-fulfillment-20240911/models/shipments_response'
require 'amz_sp_api/external-fulfillment-20240911/models/shipping_info'
require 'amz_sp_api/external-fulfillment-20240911/models/shipping_options'
require 'amz_sp_api/external-fulfillment-20240911/models/shipping_options_response'
require 'amz_sp_api/external-fulfillment-20240911/models/status'
require 'amz_sp_api/external-fulfillment-20240911/models/tax'
require 'amz_sp_api/external-fulfillment-20240911/models/tax_registration_info'
require 'amz_sp_api/external-fulfillment-20240911/models/time_window'
require 'amz_sp_api/external-fulfillment-20240911/models/weight'

# APIs
require 'amz_sp_api/external-fulfillment-20240911/api/shipment_processing_api'
require 'amz_sp_api/external-fulfillment-20240911/api/shipment_retrieval_api'

module AmzSpApi::ExternalFulfillment
  class AmzSpApi::ExternalFulfillment::V20240911::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ExternalFulfillment.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
