=begin
#The Selling Partner API for Amazon Warehousing and Distribution

#The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.

OpenAPI spec version: 2024-05-09

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/api_client'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/api_error'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/version'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/configuration'

# Models
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/address'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/carrier_code'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/carrier_code_type'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/destination_details'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/dimension_unit_of_measurement'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/distribution_package'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/distribution_package_contents'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/distribution_package_quantity'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/distribution_package_type'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/error'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/error_list'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/expiration_details'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_eligibility'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_eligibility_status'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_order'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_order_creation_data'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_order_reference'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_packages'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_preferences'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_shipment'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_shipment_status'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_shipment_summary'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inbound_status'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inventory_details'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inventory_listing'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inventory_quantity'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inventory_summary'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/inventory_unit_of_measurement'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/label_owner'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/label_status'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/measurement_data'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/order_ineligibility_reason'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/package_dimensions'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/package_volume'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/package_weight'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/prep_category'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/prep_details'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/prep_instruction'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/prep_owner'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/product_attribute'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/product_quantity'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/shipment_labels'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/shipment_listing'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/sku_eligibility'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/sku_ineligibility_reason'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/sku_quantity'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/tracking_details'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/transportation_details'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/volume_unit_of_measurement'
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/models/weight_unit_of_measurement'

# APIs
require 'amz_sp_api/amazon-warehousing-and-distribution-model-20240509/api/awd_api'

module AmzSpApi::AmazonWarehousingAndDistributionModel
  class AmzSpApi::AmazonWarehousingAndDistributionModel::V20240509::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::AmazonWarehousingAndDistributionModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
