=begin
#Selling Partner API for Direct Fulfillment Orders

#The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.

OpenAPI spec version: 2021-12-28

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/api_client'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/api_error'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/version'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/configuration'

# Models
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/acknowledgement_status'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/address'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/buyer_customized_info_detail'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/decimal'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/error'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/error_list'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/gift_details'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/item_quantity'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/money'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/order'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/order_acknowledgement_item'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/order_details'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/order_item'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/order_item_acknowledgement'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/order_list'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/pagination'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/party_identification'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/scheduled_delivery_shipment'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/shipment_dates'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/shipment_details'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/submit_acknowledgement_request'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/submit_acknowledgement_response'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/tax_details'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/tax_item_details'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/tax_line_item'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/tax_registration_details'
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/models/transaction_id'

# APIs
require 'amz_sp_api/vendor-direct-fulfillment-orders-api-model-20211228/api/vendor_orders_api'

module AmzSpApi::VendorDirectFulfillmentOrdersApiModel
  class AmzSpApi::VendorDirectFulfillmentOrdersApiModel::V20211228::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentOrdersApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
