=begin
#Selling Partner API for Supply Sources

#Manage configurations and capabilities of seller supply sources.

OpenAPI spec version: 2020-07-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::SupplySourcesApiModel
  class AmzSpApi::SupplySourcesApiModel::V20200701::TimeUnit
    HOURS = 'Hours'.freeze
    MINUTES = 'Minutes'.freeze
    DAYS = 'Days'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TimeUnit.constants.select { |c| TimeUnit::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class AmzSpApi::SupplySourcesApiModel::V20200701::#TimeUnit" if constantValues.empty?
      value
    end
  end
end
