=begin
#The Selling Partner API for Automotive.

#The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.

OpenAPI spec version: 2024-11-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/vehicles-api-model-20241101/api_client'
require 'amz_sp_api/vehicles-api-model-20241101/api_error'
require 'amz_sp_api/vehicles-api-model-20241101/version'
require 'amz_sp_api/vehicles-api-model-20241101/configuration'

# Models
require 'amz_sp_api/vehicles-api-model-20241101/models/engine_output'
require 'amz_sp_api/vehicles-api-model-20241101/models/engine_output_unit'
require 'amz_sp_api/vehicles-api-model-20241101/models/error'
require 'amz_sp_api/vehicles-api-model-20241101/models/error_list'
require 'amz_sp_api/vehicles-api-model-20241101/models/month'
require 'amz_sp_api/vehicles-api-model-20241101/models/month_and_year'
require 'amz_sp_api/vehicles-api-model-20241101/models/pagination'
require 'amz_sp_api/vehicles-api-model-20241101/models/vehicle'
require 'amz_sp_api/vehicles-api-model-20241101/models/vehicle_identifiers'
require 'amz_sp_api/vehicles-api-model-20241101/models/vehicle_standard'
require 'amz_sp_api/vehicles-api-model-20241101/models/vehicle_status_in_catalog'
require 'amz_sp_api/vehicles-api-model-20241101/models/vehicles_response'
require 'amz_sp_api/vehicles-api-model-20241101/models/year'

# APIs
require 'amz_sp_api/vehicles-api-model-20241101/api/automotive_api'
require 'amz_sp_api/vehicles-api-model-20241101/api/vehicles_api'

module AmzSpApi::VehiclesApiModel
  class AmzSpApi::VehiclesApiModel::V20241101::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VehiclesApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
