=begin
#The Selling Partner API for CustomerFeedback

#The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.

OpenAPI spec version: 2024-06-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::CustomerFeedbackApiModel::BrowseNodeReviewTopic
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BrowseNodeReviewTopic' do
  before do
    # run before each test
    @instance = AmzSpApi::CustomerFeedbackApiModel::BrowseNodeReviewTopic.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BrowseNodeReviewTopic' do
    it 'should create an instance of BrowseNodeReviewTopic' do
      expect(@instance).to be_instance_of(AmzSpApi::CustomerFeedbackApiModel::BrowseNodeReviewTopic)
    end
  end
  describe 'test attribute "topic"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "browse_node_metrics"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "review_snippets"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "subtopics"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
