=begin
#The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).

#The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.

OpenAPI spec version: 2024-03-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::SellerWalletApiModel::TransferScheduleListing
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransferScheduleListing' do
  before do
    # run before each test
    @instance = AmzSpApi::SellerWalletApiModel::TransferScheduleListing.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransferScheduleListing' do
    it 'should create an instance of TransferScheduleListing' do
      expect(@instance).to be_instance_of(AmzSpApi::SellerWalletApiModel::TransferScheduleListing)
    end
  end
  describe 'test attribute "next_page_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "transfer_schedules"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
