=begin
#Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data

#The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.

OpenAPI spec version: 2021-10-28

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/api_client'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/api_error'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/version'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/configuration'

# Models
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/error'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/error_list'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/generate_order_scenario_request'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/order_scenario_request'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/pagination'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/party_identification'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/scenario'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/test_case_data'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/test_order'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/transaction'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/transaction_reference'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/models/transaction_status'

# APIs
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/api/vendor_df_sandbox_api'
require 'amz_sp_api/vendor-direct-fulfillment-sandbox-test-data-api-model-20211028/api/vendor_df_sandboxtransactionstatus_api'

module AmzSpApi::VendorDirectFulfillmentSandboxTestDataApiModel
  class AmzSpApi::VendorDirectFulfillmentSandboxTestDataApiModel::V20211028::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentSandboxTestDataApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
