=begin
#Selling Partner API for Notifications

#The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.  For more information, refer to the [Notifications Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide).

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/notifications-api-model-0/api_client'
require 'amz_sp_api/notifications-api-model-0/api_error'
require 'amz_sp_api/notifications-api-model-0/version'
require 'amz_sp_api/notifications-api-model-0/configuration'

# Models
require 'amz_sp_api/notifications-api-model-0/models/aggregation_filter'
require 'amz_sp_api/notifications-api-model-0/models/aggregation_settings'
require 'amz_sp_api/notifications-api-model-0/models/aggregation_time_period'
require 'amz_sp_api/notifications-api-model-0/models/create_destination_request'
require 'amz_sp_api/notifications-api-model-0/models/create_destination_response'
require 'amz_sp_api/notifications-api-model-0/models/create_subscription_request'
require 'amz_sp_api/notifications-api-model-0/models/create_subscription_response'
require 'amz_sp_api/notifications-api-model-0/models/delete_destination_response'
require 'amz_sp_api/notifications-api-model-0/models/delete_subscription_by_id_response'
require 'amz_sp_api/notifications-api-model-0/models/destination'
require 'amz_sp_api/notifications-api-model-0/models/destination_list'
require 'amz_sp_api/notifications-api-model-0/models/destination_resource'
require 'amz_sp_api/notifications-api-model-0/models/destination_resource_specification'
require 'amz_sp_api/notifications-api-model-0/models/error'
require 'amz_sp_api/notifications-api-model-0/models/error_list'
require 'amz_sp_api/notifications-api-model-0/models/event_bridge_resource'
require 'amz_sp_api/notifications-api-model-0/models/event_bridge_resource_specification'
require 'amz_sp_api/notifications-api-model-0/models/event_filter'
require 'amz_sp_api/notifications-api-model-0/models/get_destination_response'
require 'amz_sp_api/notifications-api-model-0/models/get_destinations_response'
require 'amz_sp_api/notifications-api-model-0/models/get_subscription_by_id_response'
require 'amz_sp_api/notifications-api-model-0/models/get_subscription_response'
require 'amz_sp_api/notifications-api-model-0/models/marketplace_filter'
require 'amz_sp_api/notifications-api-model-0/models/marketplace_ids'
require 'amz_sp_api/notifications-api-model-0/models/order_change_type_enum'
require 'amz_sp_api/notifications-api-model-0/models/order_change_type_filter'
require 'amz_sp_api/notifications-api-model-0/models/order_change_types'
require 'amz_sp_api/notifications-api-model-0/models/processing_directive'
require 'amz_sp_api/notifications-api-model-0/models/sqs_resource'
require 'amz_sp_api/notifications-api-model-0/models/subscription'

# APIs
require 'amz_sp_api/notifications-api-model-0/api/notifications_api'

module AmzSpApi::NotificationsApiModel
  class AmzSpApi::NotificationsApiModel::V0::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::NotificationsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
