=begin
#The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).

#The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.

OpenAPI spec version: 2024-03-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::SellerWalletApiModel::TransactionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransactionsApi' do
  before do
    # run before each test
    @instance = AmzSpApi::SellerWalletApiModel::TransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionsApi' do
    it 'should create an instance of TransactionsApi' do
      expect(@instance).to be_instance_of(AmzSpApi::SellerWalletApiModel::TransactionsApi)
    end
  end

  # unit tests for create_transaction
  # Create a transaction request from Amazon SW account to another customer provided account
  # Create a transaction request from a Seller Wallet account to another customer-provided account.
  # @param body Defines the actual payload of the request
  # @param dest_account_digital_signature Digital signature for the destination bank account details. For more information, refer to [Third-Party Provider Signature Guidance](https://developer-docs.amazon.com/sp-api/docs/tpp-registration-signature-guidance).
  # @param amount_digital_signature Digital signature for the source currency transaction amount. Sign in the order of the request definitions. You can omit empty or optional fields. For more information, refer to [Third-Party Provider Signature Guidance](https://developer-docs.amazon.com/sp-api/docs/tpp-registration-signature-guidance).
  # @param marketplace_id The marketplace for which items are returned. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
  # @param [Hash] opts the optional parameters
  # @return [CreateTransactionResponse]
  describe 'create_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_transaction
  # Find particular Amazon SW account transaction by Amazon transaction identifier
  # Returns a transaction
  # @param transaction_id ID of the Amazon SW transaction
  # @param marketplace_id The marketplace for which items are returned. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
  # @param [Hash] opts the optional parameters
  # @return [Transaction]
  describe 'get_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_account_transactions
  # The API will return all the transactions for a given Amazon SW account sorted by the transaction request date
  # Retrieve a list of transactions for a given Seller Wallet bank account.
  # @param account_id ID of the Amazon SW account
  # @param marketplace_id The marketplace for which items are returned. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :next_page_token Pagination token to retrieve a specific page of results.
  # @return [TransactionListing]
  describe 'list_account_transactions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
