=begin
#The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).

#The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.

OpenAPI spec version: 2024-03-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::SellerWalletApiModel::TransferPreviewApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransferPreviewApi' do
  before do
    # run before each test
    @instance = AmzSpApi::SellerWalletApiModel::TransferPreviewApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransferPreviewApi' do
    it 'should create an instance of TransferPreviewApi' do
      expect(@instance).to be_instance_of(AmzSpApi::SellerWalletApiModel::TransferPreviewApi)
    end
  end

  # unit tests for get_transfer_preview
  # Fetch potential fees that could be applied on a transaction on the basis of the source and destination country currency code
  # Returns list of potential fees on a transaction based on the source and destination country currency code
  # @param source_country_code Represents 2 character country code of source transaction account in ISO 3166 standard format.
  # @param source_currency_code Represents 3 letter currency code in ISO 4217 standard format of the source transaction country.
  # @param destination_country_code Represents 2 character country code of destination transaction account in ISO 3166 standard format.
  # @param destination_currency_code Represents 3 letter currency code in ISO 4217 standard format of the destination transaction country.
  # @param base_amount Represents the base transaction amount without any markup fees, rates that will be used to get the transfer preview.
  # @param marketplace_id The marketplace for which items are returned. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
  # @param [Hash] opts the optional parameters
  # @return [TransferRatePreview]
  describe 'get_transfer_preview test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
