=begin
#Selling Partner API for Replenishment

#The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.

OpenAPI spec version: 2022-11-07

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/replenishment-api-model-0/api_client'
require 'amz_sp_api/replenishment-api-model-0/api_error'
require 'amz_sp_api/replenishment-api-model-0/version'
require 'amz_sp_api/replenishment-api-model-0/configuration'

# Models
require 'amz_sp_api/replenishment-api-model-0/models/aggregation_frequency'
require 'amz_sp_api/replenishment-api-model-0/models/auto_enrollment_preference'
require 'amz_sp_api/replenishment-api-model-0/models/discount_funding'
require 'amz_sp_api/replenishment-api-model-0/models/eligibility_status'
require 'amz_sp_api/replenishment-api-model-0/models/enrollment_method'
require 'amz_sp_api/replenishment-api-model-0/models/error'
require 'amz_sp_api/replenishment-api-model-0/models/error_list'
require 'amz_sp_api/replenishment-api-model-0/models/get_selling_partner_metrics_request'
require 'amz_sp_api/replenishment-api-model-0/models/get_selling_partner_metrics_response'
require 'amz_sp_api/replenishment-api-model-0/models/get_selling_partner_metrics_response_metric'
require 'amz_sp_api/replenishment-api-model-0/models/list_offer_metrics_request'
require 'amz_sp_api/replenishment-api-model-0/models/list_offer_metrics_request_filters'
require 'amz_sp_api/replenishment-api-model-0/models/list_offer_metrics_request_pagination'
require 'amz_sp_api/replenishment-api-model-0/models/list_offer_metrics_request_sort'
require 'amz_sp_api/replenishment-api-model-0/models/list_offer_metrics_response'
require 'amz_sp_api/replenishment-api-model-0/models/list_offer_metrics_response_offer'
require 'amz_sp_api/replenishment-api-model-0/models/list_offer_metrics_sort_key'
require 'amz_sp_api/replenishment-api-model-0/models/list_offers_request'
require 'amz_sp_api/replenishment-api-model-0/models/list_offers_request_filters'
require 'amz_sp_api/replenishment-api-model-0/models/list_offers_request_pagination'
require 'amz_sp_api/replenishment-api-model-0/models/list_offers_request_sort'
require 'amz_sp_api/replenishment-api-model-0/models/list_offers_response'
require 'amz_sp_api/replenishment-api-model-0/models/list_offers_response_offer'
require 'amz_sp_api/replenishment-api-model-0/models/list_offers_sort_key'
require 'amz_sp_api/replenishment-api-model-0/models/marketplace_id'
require 'amz_sp_api/replenishment-api-model-0/models/metric'
require 'amz_sp_api/replenishment-api-model-0/models/offer_program_configuration'
require 'amz_sp_api/replenishment-api-model-0/models/offer_program_configuration_preferences'
require 'amz_sp_api/replenishment-api-model-0/models/offer_program_configuration_promotions'
require 'amz_sp_api/replenishment-api-model-0/models/offer_program_configuration_promotions_discount_funding'
require 'amz_sp_api/replenishment-api-model-0/models/pagination_response'
require 'amz_sp_api/replenishment-api-model-0/models/preference'
require 'amz_sp_api/replenishment-api-model-0/models/program_type'
require 'amz_sp_api/replenishment-api-model-0/models/program_types'
require 'amz_sp_api/replenishment-api-model-0/models/promotion'
require 'amz_sp_api/replenishment-api-model-0/models/sort_order'
require 'amz_sp_api/replenishment-api-model-0/models/time_interval'
require 'amz_sp_api/replenishment-api-model-0/models/time_period_type'

# APIs
require 'amz_sp_api/replenishment-api-model-0/api/offers_api'
require 'amz_sp_api/replenishment-api-model-0/api/sellingpartners_api'

module AmzSpApi::ReplenishmentApiModel
  class AmzSpApi::ReplenishmentApiModel::V0::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ReplenishmentApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
