=begin
#Selling Partner API for Direct Fulfillment Shipping

#The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.

OpenAPI spec version: 2021-12-28

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.62
=end

require 'date'

module AmzSpApi::VendorDirectFulfillmentShippingApiModel
  class ContainerLabelFormat
    PNG = 'PNG'.freeze
    ZPL = 'ZPL'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ContainerLabelFormat.constants.select { |c| ContainerLabelFormat::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ContainerLabelFormat" if constantValues.empty?
      value
    end
  end
end
