=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ExternalFulfillment::Decimal
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Decimal' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillment::Decimal.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Decimal' do
    it 'should create an instance of Decimal' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillment::Decimal)
    end
  end
end
