=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ExternalFulfillment::LineItemWithReason
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LineItemWithReason' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillment::LineItemWithReason.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LineItemWithReason' do
    it 'should create an instance of LineItemWithReason' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillment::LineItemWithReason)
    end
  end
  describe 'test attribute "line_item"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "reason"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["OUT_OF_STOCK", "CUSTOMER_REQUESTED"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.reason = value }.not_to raise_error
      # end
    end
  end

end
