=begin
#The Selling Partner API for Amazon Warehousing and Distribution

#The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 

OpenAPI spec version: 2024-05-09

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.62
=end

# Common files
require 'amazon-warehousing-and-distribution-model/api_client'
require 'amazon-warehousing-and-distribution-model/api_error'
require 'amazon-warehousing-and-distribution-model/version'
require 'amazon-warehousing-and-distribution-model/configuration'

# Models
require 'amazon-warehousing-and-distribution-model/models/address'
require 'amazon-warehousing-and-distribution-model/models/carrier_code'
require 'amazon-warehousing-and-distribution-model/models/carrier_code_type'
require 'amazon-warehousing-and-distribution-model/models/dimension_unit_of_measurement'
require 'amazon-warehousing-and-distribution-model/models/distribution_package'
require 'amazon-warehousing-and-distribution-model/models/distribution_package_contents'
require 'amazon-warehousing-and-distribution-model/models/distribution_package_quantity'
require 'amazon-warehousing-and-distribution-model/models/distribution_package_type'
require 'amazon-warehousing-and-distribution-model/models/error'
require 'amazon-warehousing-and-distribution-model/models/error_list'
require 'amazon-warehousing-and-distribution-model/models/inbound_shipment'
require 'amazon-warehousing-and-distribution-model/models/inbound_shipment_status'
require 'amazon-warehousing-and-distribution-model/models/inbound_shipment_summary'
require 'amazon-warehousing-and-distribution-model/models/inventory_details'
require 'amazon-warehousing-and-distribution-model/models/inventory_details_visibility'
require 'amazon-warehousing-and-distribution-model/models/inventory_listing'
require 'amazon-warehousing-and-distribution-model/models/inventory_quantity'
require 'amazon-warehousing-and-distribution-model/models/inventory_summary'
require 'amazon-warehousing-and-distribution-model/models/inventory_unit_of_measurement'
require 'amazon-warehousing-and-distribution-model/models/measurement_data'
require 'amazon-warehousing-and-distribution-model/models/package_dimensions'
require 'amazon-warehousing-and-distribution-model/models/package_volume'
require 'amazon-warehousing-and-distribution-model/models/package_weight'
require 'amazon-warehousing-and-distribution-model/models/product_attribute'
require 'amazon-warehousing-and-distribution-model/models/product_quantity'
require 'amazon-warehousing-and-distribution-model/models/shipment_listing'
require 'amazon-warehousing-and-distribution-model/models/shipment_sortable_field'
require 'amazon-warehousing-and-distribution-model/models/sku_quantities_visibility'
require 'amazon-warehousing-and-distribution-model/models/sku_quantity'
require 'amazon-warehousing-and-distribution-model/models/sort_order'
require 'amazon-warehousing-and-distribution-model/models/volume_unit_of_measurement'
require 'amazon-warehousing-and-distribution-model/models/weight_unit_of_measurement'

# APIs
require 'amazon-warehousing-and-distribution-model/api/awd_api'

module AmzSpApi::AmazonWarehousingAndDistributionModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::AmazonWarehousingAndDistributionModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
