=begin
#Selling Partner API for Application Management

#The Selling Partner API for Application Management lets you programmatically update the client secret on registered applications.

OpenAPI spec version: 2023-11-30

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'application-management-api-model-20231130/api_client'
require 'application-management-api-model-20231130/api_error'
require 'application-management-api-model-20231130/version'
require 'application-management-api-model-20231130/configuration'

# Models
require 'application-management-api-model-20231130/models/error'
require 'application-management-api-model-20231130/models/error_list'

# APIs
require 'application-management-api-model-20231130/api/applications_api'

module AmzSpApi::ApplicationManagementApiModel::V20231130
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ApplicationManagementApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
