=begin
#Selling Partner API for Catalog Items

#The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'catalog-items-api-model-0/api_client'
require 'catalog-items-api-model-0/api_error'
require 'catalog-items-api-model-0/version'
require 'catalog-items-api-model-0/configuration'

# Models
require 'catalog-items-api-model-0/models/categories'
require 'catalog-items-api-model-0/models/error'
require 'catalog-items-api-model-0/models/error_list'
require 'catalog-items-api-model-0/models/list_catalog_categories_response'
require 'catalog-items-api-model-0/models/list_of_categories'

# APIs
require 'catalog-items-api-model-0/api/catalog_api'

module AmzSpApi::CatalogItemsApiModel::V0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::CatalogItemsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
