=begin
#Selling Partner API for Pricing

#The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).

OpenAPI spec version: 2022-05-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'product-pricing-api-model-20220501/api_client'
require 'product-pricing-api-model-20220501/api_error'
require 'product-pricing-api-model-20220501/version'
require 'product-pricing-api-model-20220501/configuration'

# Models
require 'product-pricing-api-model-20220501/models/asin'
require 'product-pricing-api-model-20220501/models/batch_request'
require 'product-pricing-api-model-20220501/models/batch_response'
require 'product-pricing-api-model-20220501/models/competitive_summary_batch_request'
require 'product-pricing-api-model-20220501/models/competitive_summary_batch_response'
require 'product-pricing-api-model-20220501/models/competitive_summary_included_data'
require 'product-pricing-api-model-20220501/models/competitive_summary_request'
require 'product-pricing-api-model-20220501/models/competitive_summary_request_list'
require 'product-pricing-api-model-20220501/models/competitive_summary_response'
require 'product-pricing-api-model-20220501/models/competitive_summary_response_body'
require 'product-pricing-api-model-20220501/models/competitive_summary_response_list'
require 'product-pricing-api-model-20220501/models/condition'
require 'product-pricing-api-model-20220501/models/error'
require 'product-pricing-api-model-20220501/models/error_list'
require 'product-pricing-api-model-20220501/models/errors'
require 'product-pricing-api-model-20220501/models/featured_buying_option'
require 'product-pricing-api-model-20220501/models/featured_offer'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price_request'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price_request_list'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price_request_params'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price_response'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price_response_body'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price_response_list'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price_result'
require 'product-pricing-api-model-20220501/models/featured_offer_expected_price_result_list'
require 'product-pricing-api-model-20220501/models/featured_offer_segment'
require 'product-pricing-api-model-20220501/models/fulfillment_type'
require 'product-pricing-api-model-20220501/models/get_featured_offer_expected_price_batch_request'
require 'product-pricing-api-model-20220501/models/get_featured_offer_expected_price_batch_response'
require 'product-pricing-api-model-20220501/models/http_body'
require 'product-pricing-api-model-20220501/models/http_headers'
require 'product-pricing-api-model-20220501/models/http_method'
require 'product-pricing-api-model-20220501/models/http_status_line'
require 'product-pricing-api-model-20220501/models/http_uri'
require 'product-pricing-api-model-20220501/models/lowest_priced_offer'
require 'product-pricing-api-model-20220501/models/lowest_priced_offers_input'
require 'product-pricing-api-model-20220501/models/marketplace_id'
require 'product-pricing-api-model-20220501/models/money_type'
require 'product-pricing-api-model-20220501/models/offer'
require 'product-pricing-api-model-20220501/models/offer_identifier'
require 'product-pricing-api-model-20220501/models/points'
require 'product-pricing-api-model-20220501/models/postal_code'
require 'product-pricing-api-model-20220501/models/price'
require 'product-pricing-api-model-20220501/models/prime_details'
require 'product-pricing-api-model-20220501/models/reference_price'
require 'product-pricing-api-model-20220501/models/sample_location'
require 'product-pricing-api-model-20220501/models/segment'
require 'product-pricing-api-model-20220501/models/segment_details'
require 'product-pricing-api-model-20220501/models/segmented_featured_offer'
require 'product-pricing-api-model-20220501/models/shipping_option'
require 'product-pricing-api-model-20220501/models/sku'

# APIs
require 'product-pricing-api-model-20220501/api/product_pricing_api'

module AmzSpApi::ProductPricingApiModel::V20220501
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ProductPricingApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
