=begin
#Selling Partner API for Retail Procurement Payments

#The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'vendor-invoices-api-model-0/api_client'
require 'vendor-invoices-api-model-0/api_error'
require 'vendor-invoices-api-model-0/version'
require 'vendor-invoices-api-model-0/configuration'

# Models
require 'vendor-invoices-api-model-0/models/additional_details'
require 'vendor-invoices-api-model-0/models/address'
require 'vendor-invoices-api-model-0/models/allowance_details'
require 'vendor-invoices-api-model-0/models/charge_details'
require 'vendor-invoices-api-model-0/models/credit_note_details'
require 'vendor-invoices-api-model-0/models/date_time'
require 'vendor-invoices-api-model-0/models/decimal'
require 'vendor-invoices-api-model-0/models/error'
require 'vendor-invoices-api-model-0/models/error_list'
require 'vendor-invoices-api-model-0/models/invoice'
require 'vendor-invoices-api-model-0/models/invoice_item'
require 'vendor-invoices-api-model-0/models/item_quantity'
require 'vendor-invoices-api-model-0/models/money'
require 'vendor-invoices-api-model-0/models/net_cost_unit_of_measure'
require 'vendor-invoices-api-model-0/models/party_identification'
require 'vendor-invoices-api-model-0/models/payment_terms'
require 'vendor-invoices-api-model-0/models/submit_invoices_request'
require 'vendor-invoices-api-model-0/models/submit_invoices_response'
require 'vendor-invoices-api-model-0/models/tax_details'
require 'vendor-invoices-api-model-0/models/tax_registration_details'
require 'vendor-invoices-api-model-0/models/total_weight'
require 'vendor-invoices-api-model-0/models/transaction_id'

# APIs
require 'vendor-invoices-api-model-0/api/vendor_payments_api'

module AmzSpApi::VendorInvoicesApiModel::V0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorInvoicesApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
