=begin
#Selling Partner API for Catalog Items

#The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::CatalogItemsApiModel::CatalogApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CatalogApi' do
  before do
    # run before each test
    @instance = AmzSpApi::CatalogItemsApiModel::CatalogApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CatalogApi' do
    it 'should create an instance of CatalogApi' do
      expect(@instance).to be_instance_of(AmzSpApi::CatalogItemsApiModel::CatalogApi)
    end
  end

  # unit tests for list_catalog_categories
  # Returns the parent categories to which an item belongs, based on the specified ASIN or SellerSKU.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 2 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
  # @param marketplace_id A marketplace identifier. Specifies the marketplace for the item.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :asin The Amazon Standard Identification Number (ASIN) of the item.
  # @option opts [String] :seller_sku Used to identify items in the given marketplace. SellerSKU is qualified by the seller&#x27;s SellerId, which is included with every operation that you submit.
  # @return [ListCatalogCategoriesResponse]
  describe 'list_catalog_categories test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
