=begin
#Selling Partner API for Direct Fulfillment Transaction Status

#The Selling Partner API for Direct Fulfillment Transaction Status provides programmatic access to a direct fulfillment vendor's transaction status.

OpenAPI spec version: 2021-12-28

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/api_client'
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/api_error'
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/version'
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/configuration'

# Models
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/models/error'
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/models/error_list'
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/models/transaction'
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/models/transaction_status'

# APIs
require 'amz_sp_api/vendor-direct-fulfillment-transactions-api-model-20211228/api/vendor_transaction_api'

module AmzSpApi::VendorDirectFulfillmentTransactionsApiModel
  class AmzSpApi::VendorDirectFulfillmentTransactionsApiModel::V20211228::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentTransactionsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
