=begin
#The Selling Partner API for CustomerFeedback

#The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.

OpenAPI spec version: 2024-06-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::CustomerFeedbackApiModel::CustomerFeedbackApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomerFeedbackApi' do
  before do
    # run before each test
    @instance = AmzSpApi::CustomerFeedbackApiModel::CustomerFeedbackApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerFeedbackApi' do
    it 'should create an instance of CustomerFeedbackApi' do
      expect(@instance).to be_instance_of(AmzSpApi::CustomerFeedbackApiModel::CustomerFeedbackApi)
    end
  end

  # unit tests for get_browse_node_return_topics
  # Retrieve the topics that customers mention when they return items in a browse node.
  # @param browse_node_id A browse node ID is a unique identifier for a browse node. A browse node is a named location in a browse tree that is used for navigation, product classification, and website content.
  # @param marketplace_id The MarketplaceId is the globally unique identifier of a marketplace, you can refer to the marketplaceId here : https://developer-docs.amazon.com/sp-api/docs/marketplace-ids.
  # @param [Hash] opts the optional parameters
  # @return [BrowseNodeReturnTopicsResponse]
  describe 'get_browse_node_return_topics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_browse_node_return_trends
  # Retrieve the trends of topics that customers mention when they return items in a browse node.
  # @param browse_node_id A browse node ID is a unique identifier of a browse node. A browse node is a named location in a browse tree that is used for navigation, product classification, and website content.
  # @param marketplace_id The MarketplaceId is the globally unique identifier of a marketplace, you can refer to the marketplaceId here : https://developer-docs.amazon.com/sp-api/docs/marketplace-ids.
  # @param [Hash] opts the optional parameters
  # @return [BrowseNodeReturnTrendsResponse]
  describe 'get_browse_node_return_trends test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_browse_node_review_topics
  # Retrieve a browse node&#x27;s ten most positive and ten most negative review topics.
  # @param browse_node_id The ID of a browse node. A browse node is a named location in a browse tree that is used for navigation, product classification, and website content.
  # @param marketplace_id The MarketplaceId is the globally unique identifier of a marketplace, you can refer to the marketplaceId here : https://developer-docs.amazon.com/sp-api/docs/marketplace-ids.
  # @param sort_by The metric by which to sort the data in the response.
  # @param [Hash] opts the optional parameters
  # @return [BrowseNodeReviewTopicsResponse]
  describe 'get_browse_node_review_topics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_browse_node_review_trends
  # Retrieve the positive and negative review trends of items in a browse node for the past six months.
  # @param browse_node_id A browse node ID is a unique identifier of a browse node. A browse node is a named location in a browse tree that is used for navigation, product classification, and website content.
  # @param marketplace_id The marketplace ID is the globally unique identifier of a marketplace. For more information, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
  # @param [Hash] opts the optional parameters
  # @return [BrowseNodeReviewTrendsResponse]
  describe 'get_browse_node_review_trends test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_item_browse_node
  # This API returns the associated browse node of the requested ASIN. A browse node is a location in a browse tree that is used for navigation, product classification, and website content on the Amazon retail website.
  # @param asin The Amazon Standard Identification Number (ASIN) is the unique identifier of a product within a marketplace.
  # @param marketplace_id The MarketplaceId is the globally unique identifier of a marketplace, you can refer to the marketplaceId here : https://developer-docs.amazon.com/sp-api/docs/marketplace-ids.
  # @param [Hash] opts the optional parameters
  # @return [BrowseNodeResponse]
  describe 'get_item_browse_node test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_item_review_topics
  # Retrieve an item&#x27;s ten most positive and ten most negative review topics.
  # @param asin The Amazon Standard Identification Number (ASIN) is the unique identifier of a product within a marketplace. The value must be a child ASIN.
  # @param marketplace_id The MarketplaceId is the globally unique identifier of a marketplace, you can refer to the marketplaceId here : https://developer-docs.amazon.com/sp-api/docs/marketplace-ids.
  # @param sort_by The metric by which to sort data in the response.
  # @param [Hash] opts the optional parameters
  # @return [ItemReviewTopicsResponse]
  describe 'get_item_review_topics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_item_review_trends
  # Retrieve an item&#x27;s positive and negative review trends for the past six months.
  # @param asin The Amazon Standard Identification Number (ASIN) is the unique identifier of a product within a marketplace. This API takes child ASIN as an input.
  # @param marketplace_id The MarketplaceId is the globally unique identifier of a marketplace, you can refer to the marketplaceId here : https://developer-docs.amazon.com/sp-api/docs/marketplace-ids.
  # @param [Hash] opts the optional parameters
  # @return [ItemReviewTrendsResponse]
  describe 'get_item_review_trends test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
