=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::ExternalFulfillment::V20240911
  class PresenceStatus
    ABSENT = 'ABSENT'.freeze
    PRESENT = 'PRESENT'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PresenceStatus.constants.select { |c| PresenceStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PresenceStatus" if constantValues.empty?
      value
    end
  end
end
