=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::ExternalFulfillment::V20240911
  # Information about a shipment.
  class Shipment
    # The shipment's ID.
    attr_accessor :id

    # The location identifier of the seller's location in the marketplace channel to which the shipment has been created for fulfillment.
    attr_accessor :location_id

    attr_accessor :marketplace_attributes

    attr_accessor :shipment_info

    attr_accessor :invoice_info

    attr_accessor :party_info_list

    attr_accessor :shipment_requirements

    attr_accessor :charges

    # The current status of the shipment.
    attr_accessor :status

    # The sub status of the shipment.
    attr_accessor :sub_status

    # The reason for the sub-status.
    attr_accessor :reason

    # The line items in the shipment.
    attr_accessor :line_items

    attr_accessor :shipping_info

    # The list of packages in the shipment.
    attr_accessor :packages

    attr_accessor :creation_date_time

    attr_accessor :last_updated_date_time

    attr_accessor :earliest_pack_date_time

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'location_id' => :'locationId',
        :'marketplace_attributes' => :'marketplaceAttributes',
        :'shipment_info' => :'shipmentInfo',
        :'invoice_info' => :'invoiceInfo',
        :'party_info_list' => :'partyInfoList',
        :'shipment_requirements' => :'shipmentRequirements',
        :'charges' => :'charges',
        :'status' => :'status',
        :'sub_status' => :'subStatus',
        :'reason' => :'reason',
        :'line_items' => :'lineItems',
        :'shipping_info' => :'shippingInfo',
        :'packages' => :'packages',
        :'creation_date_time' => :'creationDateTime',
        :'last_updated_date_time' => :'lastUpdatedDateTime',
        :'earliest_pack_date_time' => :'earliestPackDateTime'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Object',
        :'location_id' => :'Object',
        :'marketplace_attributes' => :'Object',
        :'shipment_info' => :'Object',
        :'invoice_info' => :'Object',
        :'party_info_list' => :'Object',
        :'shipment_requirements' => :'Object',
        :'charges' => :'Object',
        :'status' => :'Object',
        :'sub_status' => :'Object',
        :'reason' => :'Object',
        :'line_items' => :'Object',
        :'shipping_info' => :'Object',
        :'packages' => :'Object',
        :'creation_date_time' => :'Object',
        :'last_updated_date_time' => :'Object',
        :'earliest_pack_date_time' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AmzSpApi::ExternalFulfillment::Shipment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AmzSpApi::ExternalFulfillment::Shipment`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'location_id')
        self.location_id = attributes[:'location_id']
      end

      if attributes.key?(:'marketplace_attributes')
        self.marketplace_attributes = attributes[:'marketplace_attributes']
      end

      if attributes.key?(:'shipment_info')
        self.shipment_info = attributes[:'shipment_info']
      end

      if attributes.key?(:'invoice_info')
        self.invoice_info = attributes[:'invoice_info']
      end

      if attributes.key?(:'party_info_list')
        self.party_info_list = attributes[:'party_info_list']
      end

      if attributes.key?(:'shipment_requirements')
        self.shipment_requirements = attributes[:'shipment_requirements']
      end

      if attributes.key?(:'charges')
        self.charges = attributes[:'charges']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'sub_status')
        self.sub_status = attributes[:'sub_status']
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      end

      if attributes.key?(:'line_items')
        if (value = attributes[:'line_items']).is_a?(Array)
          self.line_items = value
        end
      end

      if attributes.key?(:'shipping_info')
        self.shipping_info = attributes[:'shipping_info']
      end

      if attributes.key?(:'packages')
        if (value = attributes[:'packages']).is_a?(Array)
          self.packages = value
        end
      end

      if attributes.key?(:'creation_date_time')
        self.creation_date_time = attributes[:'creation_date_time']
      end

      if attributes.key?(:'last_updated_date_time')
        self.last_updated_date_time = attributes[:'last_updated_date_time']
      end

      if attributes.key?(:'earliest_pack_date_time')
        self.earliest_pack_date_time = attributes[:'earliest_pack_date_time']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @location_id.nil?
        invalid_properties.push('invalid value for "location_id", location_id cannot be nil.')
      end

      if @marketplace_attributes.nil?
        invalid_properties.push('invalid value for "marketplace_attributes", marketplace_attributes cannot be nil.')
      end

      if @shipment_info.nil?
        invalid_properties.push('invalid value for "shipment_info", shipment_info cannot be nil.')
      end

      if @shipment_requirements.nil?
        invalid_properties.push('invalid value for "shipment_requirements", shipment_requirements cannot be nil.')
      end

      if @charges.nil?
        invalid_properties.push('invalid value for "charges", charges cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @line_items.nil?
        invalid_properties.push('invalid value for "line_items", line_items cannot be nil.')
      end

      if @shipping_info.nil?
        invalid_properties.push('invalid value for "shipping_info", shipping_info cannot be nil.')
      end

      if @creation_date_time.nil?
        invalid_properties.push('invalid value for "creation_date_time", creation_date_time cannot be nil.')
      end

      if @last_updated_date_time.nil?
        invalid_properties.push('invalid value for "last_updated_date_time", last_updated_date_time cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @location_id.nil?
      return false if @marketplace_attributes.nil?
      return false if @shipment_info.nil?
      return false if @shipment_requirements.nil?
      return false if @charges.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('Object', ['CREATED', 'ACCEPTED', 'CONFIRMED', 'PACKAGE_CREATED', 'PICKUP_SLOT_RETRIEVED', 'INVOICE_GENERATED', 'SHIPLABEL_GENERATED', 'CANCELLED', 'SHIPPED', 'DELIVERED'])
      return false unless status_validator.valid?(@status)
      sub_status_validator = EnumAttributeValidator.new('Object', ['PENDING_SCHEDULE', 'PENDING_PICKUP', 'PENDING_DROP_OFF', 'LABEL_CANCELED', 'PICKED_UP', 'DROPPED_OFF', 'AT_ORIGIN_FC', 'AT_DESTINATION_FC', 'DELIVERED', 'NOT_DELIVERED', 'UNDELIVERABLE', 'LOST', 'OUT_FOR_DELIVERY', 'DAMAGED'])
      return false unless sub_status_validator.valid?(@sub_status)
      return false if @line_items.nil?
      return false if @shipping_info.nil?
      return false if @creation_date_time.nil?
      return false if @last_updated_date_time.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('Object', ['CREATED', 'ACCEPTED', 'CONFIRMED', 'PACKAGE_CREATED', 'PICKUP_SLOT_RETRIEVED', 'INVOICE_GENERATED', 'SHIPLABEL_GENERATED', 'CANCELLED', 'SHIPPED', 'DELIVERED'])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sub_status Object to be assigned
    def sub_status=(sub_status)
      validator = EnumAttributeValidator.new('Object', ['PENDING_SCHEDULE', 'PENDING_PICKUP', 'PENDING_DROP_OFF', 'LABEL_CANCELED', 'PICKED_UP', 'DROPPED_OFF', 'AT_ORIGIN_FC', 'AT_DESTINATION_FC', 'DELIVERED', 'NOT_DELIVERED', 'UNDELIVERABLE', 'LOST', 'OUT_FOR_DELIVERY', 'DAMAGED'])
      unless validator.valid?(sub_status)
        fail ArgumentError, "invalid value for \"sub_status\", must be one of #{validator.allowable_values}."
      end
      @sub_status = sub_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          location_id == o.location_id &&
          marketplace_attributes == o.marketplace_attributes &&
          shipment_info == o.shipment_info &&
          invoice_info == o.invoice_info &&
          party_info_list == o.party_info_list &&
          shipment_requirements == o.shipment_requirements &&
          charges == o.charges &&
          status == o.status &&
          sub_status == o.sub_status &&
          reason == o.reason &&
          line_items == o.line_items &&
          shipping_info == o.shipping_info &&
          packages == o.packages &&
          creation_date_time == o.creation_date_time &&
          last_updated_date_time == o.last_updated_date_time &&
          earliest_pack_date_time == o.earliest_pack_date_time
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, location_id, marketplace_attributes, shipment_info, invoice_info, party_info_list, shipment_requirements, charges, status, sub_status, reason, line_items, shipping_info, packages, creation_date_time, last_updated_date_time, earliest_pack_date_time].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmzSpApi::ExternalFulfillment::V20240911.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
