=begin
#Selling Partner API for Shipment Invoicing

#The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/shipment-invoicing-api-model-0/api_client'
require 'amz_sp_api/shipment-invoicing-api-model-0/api_error'
require 'amz_sp_api/shipment-invoicing-api-model-0/version'
require 'amz_sp_api/shipment-invoicing-api-model-0/configuration'

# Models
require 'amz_sp_api/shipment-invoicing-api-model-0/models/address'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/address_type_enum'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/blob'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/buyer_tax_info'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/error'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/error_list'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/get_invoice_status_response'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/get_shipment_details_response'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/marketplace_tax_info'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/money'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/payment_information'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/payment_information_list'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/payment_method_detail_item_list'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/payment_method_enum'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/serial_numbers_list'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/shipment_detail'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/shipment_invoice_status'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/shipment_invoice_status_info'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/shipment_invoice_status_response'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/shipment_item'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/shipment_items'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/submit_invoice_request'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/submit_invoice_response'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/tax_classification'
require 'amz_sp_api/shipment-invoicing-api-model-0/models/tax_classification_list'

# APIs
require 'amz_sp_api/shipment-invoicing-api-model-0/api/shipment_invoice_api'

module AmzSpApi::ShipmentInvoicingApiModel
  class AmzSpApi::ShipmentInvoicingApiModel::V0::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ShipmentInvoicingApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
