=begin
#The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).

#The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.

OpenAPI spec version: 2024-03-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::SellerWalletApiModel
  # Details of an Amazon Seller Wallet bank account. This account is used to hold the money that a Seller Wallet customer earns by selling items.
  class BankAccount
    # The unique bank account identifier provided by Amazon. To initiate a `SELF` transaction with Seller Wallet, you must choose `BANK_ACCOUNT` as the payment method type in the [getPaymentMethod](https://developer-docs.amazon.com/sp-api/reference/getpaymentmethods) request. Your Amazon Seller Wallet bank account identifier should match the `paymentMethodId` in the response. This field is required.
    attr_accessor :account_id

    # The bank account holder's name (expected to be an Amazon customer). There is a 50 character limit.
    attr_accessor :account_holder_name

    attr_accessor :bank_account_number_format

    # The name of the bank. This value is Amazon Seller Wallet for Amazon Seller Wallet accounts.
    attr_accessor :bank_name

    attr_accessor :bank_account_ownership_type

    # Routing number for automated clearing house transfers for `THIRD_PARTY` transaction requests. This value is nine consecutive zeros for Amazon Seller Wallet accounts.
    attr_accessor :routing_number

    attr_accessor :bank_number_format

    # The two digit country code, in ISO 3166 format. 
    attr_accessor :account_country_code

    # BankAccount currency code in ISO 4217 format 
    attr_accessor :account_currency

    # Last 3 digit of the bank account number, for all Amazon Seller Wallet account the value will be three consecutive 0's 
    attr_accessor :bank_account_number_tail

    attr_accessor :bank_account_holder_status

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountId',
        :'account_holder_name' => :'accountHolderName',
        :'bank_account_number_format' => :'bankAccountNumberFormat',
        :'bank_name' => :'bankName',
        :'bank_account_ownership_type' => :'bankAccountOwnershipType',
        :'routing_number' => :'routingNumber',
        :'bank_number_format' => :'bankNumberFormat',
        :'account_country_code' => :'accountCountryCode',
        :'account_currency' => :'accountCurrency',
        :'bank_account_number_tail' => :'bankAccountNumberTail',
        :'bank_account_holder_status' => :'bankAccountHolderStatus'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'Object',
        :'account_holder_name' => :'Object',
        :'bank_account_number_format' => :'Object',
        :'bank_name' => :'Object',
        :'bank_account_ownership_type' => :'Object',
        :'routing_number' => :'Object',
        :'bank_number_format' => :'Object',
        :'account_country_code' => :'Object',
        :'account_currency' => :'Object',
        :'bank_account_number_tail' => :'Object',
        :'bank_account_holder_status' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AmzSpApi::SellerWalletApiModel::BankAccount` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AmzSpApi::SellerWalletApiModel::BankAccount`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'account_holder_name')
        self.account_holder_name = attributes[:'account_holder_name']
      end

      if attributes.key?(:'bank_account_number_format')
        self.bank_account_number_format = attributes[:'bank_account_number_format']
      end

      if attributes.key?(:'bank_name')
        self.bank_name = attributes[:'bank_name']
      end

      if attributes.key?(:'bank_account_ownership_type')
        self.bank_account_ownership_type = attributes[:'bank_account_ownership_type']
      end

      if attributes.key?(:'routing_number')
        self.routing_number = attributes[:'routing_number']
      end

      if attributes.key?(:'bank_number_format')
        self.bank_number_format = attributes[:'bank_number_format']
      end

      if attributes.key?(:'account_country_code')
        self.account_country_code = attributes[:'account_country_code']
      end

      if attributes.key?(:'account_currency')
        self.account_currency = attributes[:'account_currency']
      end

      if attributes.key?(:'bank_account_number_tail')
        self.bank_account_number_tail = attributes[:'bank_account_number_tail']
      end

      if attributes.key?(:'bank_account_holder_status')
        self.bank_account_holder_status = attributes[:'bank_account_holder_status']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @bank_account_ownership_type.nil?
        invalid_properties.push('invalid value for "bank_account_ownership_type", bank_account_ownership_type cannot be nil.')
      end

      if @account_country_code.nil?
        invalid_properties.push('invalid value for "account_country_code", account_country_code cannot be nil.')
      end

      if @account_currency.nil?
        invalid_properties.push('invalid value for "account_currency", account_currency cannot be nil.')
      end

      if @bank_account_number_tail.nil?
        invalid_properties.push('invalid value for "bank_account_number_tail", bank_account_number_tail cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @bank_account_ownership_type.nil?
      return false if @account_country_code.nil?
      return false if @account_currency.nil?
      return false if @bank_account_number_tail.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          account_holder_name == o.account_holder_name &&
          bank_account_number_format == o.bank_account_number_format &&
          bank_name == o.bank_name &&
          bank_account_ownership_type == o.bank_account_ownership_type &&
          routing_number == o.routing_number &&
          bank_number_format == o.bank_number_format &&
          account_country_code == o.account_country_code &&
          account_currency == o.account_currency &&
          bank_account_number_tail == o.bank_account_number_tail &&
          bank_account_holder_status == o.bank_account_holder_status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, account_holder_name, bank_account_number_format, bank_name, bank_account_ownership_type, routing_number, bank_number_format, account_country_code, account_currency, bank_account_number_tail, bank_account_holder_status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmzSpApi::SellerWalletApiModel.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
