=begin
#The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).

#The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.

OpenAPI spec version: 2024-03-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::SellerWalletApiModel
  # Transfer schedule details and related historical details.
  class TransferSchedule
    # The unique identifier provided by Amazon to the scheduled transfer 
    attr_accessor :transfer_schedule_id

    attr_accessor :transaction_type

    attr_accessor :transaction_source_account

    attr_accessor :transaction_destination_account

    attr_accessor :transfer_schedule_status

    attr_accessor :transfer_schedule_information

    attr_accessor :payment_preference

    # Collection that holds Transfer Schedules that has been cancelled or failed due to certain reasons. 
    attr_accessor :transfer_schedule_failures

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'transfer_schedule_id' => :'transferScheduleId',
        :'transaction_type' => :'transactionType',
        :'transaction_source_account' => :'transactionSourceAccount',
        :'transaction_destination_account' => :'transactionDestinationAccount',
        :'transfer_schedule_status' => :'transferScheduleStatus',
        :'transfer_schedule_information' => :'transferScheduleInformation',
        :'payment_preference' => :'paymentPreference',
        :'transfer_schedule_failures' => :'transferScheduleFailures'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'transfer_schedule_id' => :'Object',
        :'transaction_type' => :'Object',
        :'transaction_source_account' => :'Object',
        :'transaction_destination_account' => :'Object',
        :'transfer_schedule_status' => :'Object',
        :'transfer_schedule_information' => :'Object',
        :'payment_preference' => :'Object',
        :'transfer_schedule_failures' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AmzSpApi::SellerWalletApiModel::TransferSchedule` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AmzSpApi::SellerWalletApiModel::TransferSchedule`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'transfer_schedule_id')
        self.transfer_schedule_id = attributes[:'transfer_schedule_id']
      end

      if attributes.key?(:'transaction_type')
        self.transaction_type = attributes[:'transaction_type']
      end

      if attributes.key?(:'transaction_source_account')
        self.transaction_source_account = attributes[:'transaction_source_account']
      end

      if attributes.key?(:'transaction_destination_account')
        self.transaction_destination_account = attributes[:'transaction_destination_account']
      end

      if attributes.key?(:'transfer_schedule_status')
        self.transfer_schedule_status = attributes[:'transfer_schedule_status']
      end

      if attributes.key?(:'transfer_schedule_information')
        self.transfer_schedule_information = attributes[:'transfer_schedule_information']
      end

      if attributes.key?(:'payment_preference')
        self.payment_preference = attributes[:'payment_preference']
      end

      if attributes.key?(:'transfer_schedule_failures')
        if (value = attributes[:'transfer_schedule_failures']).is_a?(Array)
          self.transfer_schedule_failures = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @transfer_schedule_id.nil?
        invalid_properties.push('invalid value for "transfer_schedule_id", transfer_schedule_id cannot be nil.')
      end

      if @transaction_type.nil?
        invalid_properties.push('invalid value for "transaction_type", transaction_type cannot be nil.')
      end

      if @transaction_destination_account.nil?
        invalid_properties.push('invalid value for "transaction_destination_account", transaction_destination_account cannot be nil.')
      end

      if @transfer_schedule_status.nil?
        invalid_properties.push('invalid value for "transfer_schedule_status", transfer_schedule_status cannot be nil.')
      end

      if @transfer_schedule_information.nil?
        invalid_properties.push('invalid value for "transfer_schedule_information", transfer_schedule_information cannot be nil.')
      end

      if @transfer_schedule_failures.nil?
        invalid_properties.push('invalid value for "transfer_schedule_failures", transfer_schedule_failures cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @transfer_schedule_id.nil?
      return false if @transaction_type.nil?
      return false if @transaction_destination_account.nil?
      return false if @transfer_schedule_status.nil?
      return false if @transfer_schedule_information.nil?
      return false if @transfer_schedule_failures.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          transfer_schedule_id == o.transfer_schedule_id &&
          transaction_type == o.transaction_type &&
          transaction_source_account == o.transaction_source_account &&
          transaction_destination_account == o.transaction_destination_account &&
          transfer_schedule_status == o.transfer_schedule_status &&
          transfer_schedule_information == o.transfer_schedule_information &&
          payment_preference == o.payment_preference &&
          transfer_schedule_failures == o.transfer_schedule_failures
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [transfer_schedule_id, transaction_type, transaction_source_account, transaction_destination_account, transfer_schedule_status, transfer_schedule_information, payment_preference, transfer_schedule_failures].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmzSpApi::SellerWalletApiModel.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
