=begin
#The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).

#The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.

OpenAPI spec version: 2024-03-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::SellerWalletApiModel
  # The current transaction status and related historical details.
  class Transaction
    # The unique identifier of the Amazon Seller Wallet bank account from which the money is debited.
    attr_accessor :account_id

    # The unique identifier provided by Amazon to the transaction 
    attr_accessor :transaction_id

    attr_accessor :transaction_type

    attr_accessor :transaction_status

    # The date when the transaction was initiated.
    attr_accessor :transaction_request_date

    # Expected completion date of a transaction, for existing active Payees (Trusted Beneficiaries) it will be 24 hours but for new destination bank accounts the value could go up to 5 days 
    attr_accessor :expected_completion_date

    # Transaction completion date 
    attr_accessor :transaction_actual_completion_date

    # The last update date on the transaction 
    attr_accessor :last_update_date

    # Amazon SW customer who requested the transaction 
    attr_accessor :requester_name

    # The transaction initiation source. This value is either the Amazon portal or PISP name that the customer used to start the transaction.
    attr_accessor :transaction_requester_source

    # A description of the transaction that the requester provides when they initiate the transaction.
    attr_accessor :transaction_description

    attr_accessor :transaction_source_account

    attr_accessor :transaction_destination_account

    attr_accessor :transaction_request_amount

    attr_accessor :transfer_rate_details

    attr_accessor :transaction_final_amount

    # Description in case the transaction fails before completion 
    attr_accessor :transaction_failure_reason

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountId',
        :'transaction_id' => :'transactionId',
        :'transaction_type' => :'transactionType',
        :'transaction_status' => :'transactionStatus',
        :'transaction_request_date' => :'transactionRequestDate',
        :'expected_completion_date' => :'expectedCompletionDate',
        :'transaction_actual_completion_date' => :'transactionActualCompletionDate',
        :'last_update_date' => :'lastUpdateDate',
        :'requester_name' => :'requesterName',
        :'transaction_requester_source' => :'transactionRequesterSource',
        :'transaction_description' => :'transactionDescription',
        :'transaction_source_account' => :'transactionSourceAccount',
        :'transaction_destination_account' => :'transactionDestinationAccount',
        :'transaction_request_amount' => :'transactionRequestAmount',
        :'transfer_rate_details' => :'transferRateDetails',
        :'transaction_final_amount' => :'transactionFinalAmount',
        :'transaction_failure_reason' => :'transactionFailureReason'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'Object',
        :'transaction_id' => :'Object',
        :'transaction_type' => :'Object',
        :'transaction_status' => :'Object',
        :'transaction_request_date' => :'Object',
        :'expected_completion_date' => :'Object',
        :'transaction_actual_completion_date' => :'Object',
        :'last_update_date' => :'Object',
        :'requester_name' => :'Object',
        :'transaction_requester_source' => :'Object',
        :'transaction_description' => :'Object',
        :'transaction_source_account' => :'Object',
        :'transaction_destination_account' => :'Object',
        :'transaction_request_amount' => :'Object',
        :'transfer_rate_details' => :'Object',
        :'transaction_final_amount' => :'Object',
        :'transaction_failure_reason' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AmzSpApi::SellerWalletApiModel::Transaction` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AmzSpApi::SellerWalletApiModel::Transaction`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'transaction_id')
        self.transaction_id = attributes[:'transaction_id']
      end

      if attributes.key?(:'transaction_type')
        self.transaction_type = attributes[:'transaction_type']
      end

      if attributes.key?(:'transaction_status')
        self.transaction_status = attributes[:'transaction_status']
      end

      if attributes.key?(:'transaction_request_date')
        self.transaction_request_date = attributes[:'transaction_request_date']
      end

      if attributes.key?(:'expected_completion_date')
        self.expected_completion_date = attributes[:'expected_completion_date']
      end

      if attributes.key?(:'transaction_actual_completion_date')
        self.transaction_actual_completion_date = attributes[:'transaction_actual_completion_date']
      end

      if attributes.key?(:'last_update_date')
        self.last_update_date = attributes[:'last_update_date']
      end

      if attributes.key?(:'requester_name')
        self.requester_name = attributes[:'requester_name']
      end

      if attributes.key?(:'transaction_requester_source')
        self.transaction_requester_source = attributes[:'transaction_requester_source']
      end

      if attributes.key?(:'transaction_description')
        self.transaction_description = attributes[:'transaction_description']
      end

      if attributes.key?(:'transaction_source_account')
        self.transaction_source_account = attributes[:'transaction_source_account']
      end

      if attributes.key?(:'transaction_destination_account')
        self.transaction_destination_account = attributes[:'transaction_destination_account']
      end

      if attributes.key?(:'transaction_request_amount')
        self.transaction_request_amount = attributes[:'transaction_request_amount']
      end

      if attributes.key?(:'transfer_rate_details')
        self.transfer_rate_details = attributes[:'transfer_rate_details']
      end

      if attributes.key?(:'transaction_final_amount')
        self.transaction_final_amount = attributes[:'transaction_final_amount']
      end

      if attributes.key?(:'transaction_failure_reason')
        self.transaction_failure_reason = attributes[:'transaction_failure_reason']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @transaction_id.nil?
        invalid_properties.push('invalid value for "transaction_id", transaction_id cannot be nil.')
      end

      if @transaction_type.nil?
        invalid_properties.push('invalid value for "transaction_type", transaction_type cannot be nil.')
      end

      if @transaction_status.nil?
        invalid_properties.push('invalid value for "transaction_status", transaction_status cannot be nil.')
      end

      if @transaction_request_date.nil?
        invalid_properties.push('invalid value for "transaction_request_date", transaction_request_date cannot be nil.')
      end

      if @last_update_date.nil?
        invalid_properties.push('invalid value for "last_update_date", last_update_date cannot be nil.')
      end

      if @transaction_requester_source.nil?
        invalid_properties.push('invalid value for "transaction_requester_source", transaction_requester_source cannot be nil.')
      end

      if @transaction_description.nil?
        invalid_properties.push('invalid value for "transaction_description", transaction_description cannot be nil.')
      end

      if @transaction_destination_account.nil?
        invalid_properties.push('invalid value for "transaction_destination_account", transaction_destination_account cannot be nil.')
      end

      if @transaction_request_amount.nil?
        invalid_properties.push('invalid value for "transaction_request_amount", transaction_request_amount cannot be nil.')
      end

      if @transfer_rate_details.nil?
        invalid_properties.push('invalid value for "transfer_rate_details", transfer_rate_details cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @account_id.nil?
      return false if @transaction_id.nil?
      return false if @transaction_type.nil?
      return false if @transaction_status.nil?
      return false if @transaction_request_date.nil?
      return false if @last_update_date.nil?
      return false if @transaction_requester_source.nil?
      return false if @transaction_description.nil?
      return false if @transaction_destination_account.nil?
      return false if @transaction_request_amount.nil?
      return false if @transfer_rate_details.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          transaction_id == o.transaction_id &&
          transaction_type == o.transaction_type &&
          transaction_status == o.transaction_status &&
          transaction_request_date == o.transaction_request_date &&
          expected_completion_date == o.expected_completion_date &&
          transaction_actual_completion_date == o.transaction_actual_completion_date &&
          last_update_date == o.last_update_date &&
          requester_name == o.requester_name &&
          transaction_requester_source == o.transaction_requester_source &&
          transaction_description == o.transaction_description &&
          transaction_source_account == o.transaction_source_account &&
          transaction_destination_account == o.transaction_destination_account &&
          transaction_request_amount == o.transaction_request_amount &&
          transfer_rate_details == o.transfer_rate_details &&
          transaction_final_amount == o.transaction_final_amount &&
          transaction_failure_reason == o.transaction_failure_reason
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, transaction_id, transaction_type, transaction_status, transaction_request_date, expected_completion_date, transaction_actual_completion_date, last_update_date, requester_name, transaction_requester_source, transaction_description, transaction_source_account, transaction_destination_account, transaction_request_amount, transfer_rate_details, transaction_final_amount, transaction_failure_reason].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmzSpApi::SellerWalletApiModel.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
