=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::ExternalFulfillment::ShipmentProcessingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShipmentProcessingApi' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillment::ShipmentProcessingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShipmentProcessingApi' do
    it 'should create an instance of ShipmentProcessingApi' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillment::ShipmentProcessingApi)
    end
  end

  # unit tests for create_packages
  # Provide details about the packages in the specified shipment.
  # @param body A list of packages in the shipment.
  # @param shipment_id The ID of the shipment.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_packages test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for generate_invoice
  # Get invoices for the shipment you specify.
  # @param shipment_id The ID of the shipment whose invoice you want.
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'generate_invoice test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for generate_ship_labels
  # Generate and retrieve all shipping labels for one or more packages in the shipment you specify.
  # @param operation Specify whether you want to generate or regenerate a label.
  # @param shipment_id The ID of the shipment whose shipping labels you want to generate and retrieve.
  # @param [Hash] opts the optional parameters
  # @option opts [ShipLabelsInput] :body Shipping details for when shipping is not done by the marketplace channel.
  # @option opts [String] :shipping_option_id The ID of the shipping option whose shipping labels you want.
  # @return [ShipLabelsResponse]
  describe 'generate_ship_labels test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for process_shipment
  # Confirm or reject the specified shipment.
  # @param operation The status of the shipment.
  # @param shipment_id The ID of the shipment you want to confirm or reject.
  # @param [Hash] opts the optional parameters
  # @option opts [ShipmentAcknowledgementRequest] :body Information about the shipment and its line items.
  # @return [nil]
  describe 'process_shipment test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retrieve_invoice
  # Retrieve invoices for the shipment you specify.
  # @param shipment_id The ID of the shipment whose invoice you want to retrieve.
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'retrieve_invoice test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retrieve_shipping_options
  # Get a list of shipping options for a package in a shipment given the shipment&#x27;s marketplace and channel. If the marketplace and channel have a pre-determined shipping option, then this operation returns an empty response.
  # @param shipment_id The ID of the shipment to which the package belongs.
  # @param package_id The ID of the package for which you want to retrieve shipping options.
  # @param [Hash] opts the optional parameters
  # @return [ShippingOptionsResponse]
  describe 'retrieve_shipping_options test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_package
  # Updates the details about the packages that will be used to fulfill the specified shipment.
  # @param body The body of the request.
  # @param shipment_id The ID of the shipment to which the package belongs.
  # @param package_id The ID of the package whose information you want to update.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_package test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_package_status
  # Updates the status of the packages.
  # @param shipment_id The ID of the shipment to which the package belongs.
  # @param package_id The ID of the package whose status you want to update.
  # @param [Hash] opts the optional parameters
  # @option opts [PackageDeliveryStatus] :body The body of the request.
  # @option opts [String] :status **DEPRECATED**. Do not use. Package status is defined in the body parameter.
  # @return [nil]
  describe 'update_package_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
