=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::ExternalFulfillment::ShipmentRetrievalApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShipmentRetrievalApi' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillment::ShipmentRetrievalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShipmentRetrievalApi' do
    it 'should create an instance of ShipmentRetrievalApi' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillment::ShipmentRetrievalApi)
    end
  end

  # unit tests for get_shipment
  # Get a single shipment with the ID you specify.
  # @param shipment_id The ID of the shipment you want to retrieve.
  # @param [Hash] opts the optional parameters
  # @return [Shipment]
  describe 'get_shipment test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_shipments
  # Get a list of shipments created for the seller in the status you specify. Shipments can be further filtered based on the fulfillment node or the time of the shipments&#x27; last update.
  # @param status The status of shipment you want to include in the response. To retrieve all new shipments, set this value to &#x60;ACCEPTED&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :location_id The Amazon channel location identifier for the shipments you want to retrieve.
  # @option opts [String] :marketplace_id The marketplace ID associated with the location. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
  # @option opts [String] :channel_name The channel name associated with the location.
  # @option opts [DateTime] :last_updated_after The response includes shipments whose latest update is after the specified time. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
  # @option opts [DateTime] :last_updated_before The response includes shipments whose latest update is before the specified time. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
  # @option opts [Integer] :max_results The maximum number of shipments to include in the response.
  # @option opts [String] :pagination_token A token that you use to retrieve the next page of results. The response includes &#x60;nextToken&#x60; when there are multiple pages of results. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until &#x60;nextToken&#x60; is null. Note that this operation can return empty pages.
  # @return [ShipmentsResponse]
  describe 'get_shipments test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
