=begin
#Selling Partner API for Data Kiosk

#The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.

OpenAPI spec version: 2023-11-15

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/data-kiosk-api-model-20231115/api_client'
require 'amz_sp_api/data-kiosk-api-model-20231115/api_error'
require 'amz_sp_api/data-kiosk-api-model-20231115/version'
require 'amz_sp_api/data-kiosk-api-model-20231115/configuration'

# Models
require 'amz_sp_api/data-kiosk-api-model-20231115/models/create_query_response'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/create_query_specification'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/error'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/error_list'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/get_document_response'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/get_queries_response'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/get_queries_response_pagination'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/query'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/query_list'
require 'amz_sp_api/data-kiosk-api-model-20231115/models/query_pagination'

# APIs
require 'amz_sp_api/data-kiosk-api-model-20231115/api/queries_api'

module AmzSpApi::DataKioskApiModel
  class AmzSpApi::DataKioskApiModel::V20231115::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::DataKioskApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
