=begin
#Selling Partner API for Direct Fulfillment Inventory Updates

#The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/api_client'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/api_error'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/version'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/configuration'

# Models
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/error'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/error_list'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/inventory_update'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/item_details'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/item_quantity'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/party_identification'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/submit_inventory_update_request'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/submit_inventory_update_response'
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/models/transaction_reference'

# APIs
require 'amz_sp_api/vendor-direct-fulfillment-inventory-api-model-0/api/update_inventory_api'

module AmzSpApi::VendorDirectFulfillmentInventoryApiModel
  class AmzSpApi::VendorDirectFulfillmentInventoryApiModel::V0::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentInventoryApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
