=begin
#Selling Partner API for Retail Procurement Shipments

#The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'amz_sp_api/vendor-shipments-api-model-0/api_client'
require 'amz_sp_api/vendor-shipments-api-model-0/api_error'
require 'amz_sp_api/vendor-shipments-api-model-0/version'
require 'amz_sp_api/vendor-shipments-api-model-0/configuration'

# Models
require 'amz_sp_api/vendor-shipments-api-model-0/models/address'
require 'amz_sp_api/vendor-shipments-api-model-0/models/carrier_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/carton'
require 'amz_sp_api/vendor-shipments-api-model-0/models/carton_reference_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/collect_freight_pickup_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/container_identification'
require 'amz_sp_api/vendor-shipments-api-model-0/models/container_item'
require 'amz_sp_api/vendor-shipments-api-model-0/models/container_sequence_numbers'
require 'amz_sp_api/vendor-shipments-api-model-0/models/containers'
require 'amz_sp_api/vendor-shipments-api-model-0/models/decimal'
require 'amz_sp_api/vendor-shipments-api-model-0/models/dimensions'
require 'amz_sp_api/vendor-shipments-api-model-0/models/duration'
require 'amz_sp_api/vendor-shipments-api-model-0/models/error'
require 'amz_sp_api/vendor-shipments-api-model-0/models/error_list'
require 'amz_sp_api/vendor-shipments-api-model-0/models/expiry'
require 'amz_sp_api/vendor-shipments-api-model-0/models/get_shipment_details_response'
require 'amz_sp_api/vendor-shipments-api-model-0/models/get_shipment_labels'
require 'amz_sp_api/vendor-shipments-api-model-0/models/import_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/inner_containers_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/item'
require 'amz_sp_api/vendor-shipments-api-model-0/models/item_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/item_quantity'
require 'amz_sp_api/vendor-shipments-api-model-0/models/label_data'
require 'amz_sp_api/vendor-shipments-api-model-0/models/location'
require 'amz_sp_api/vendor-shipments-api-model-0/models/money'
require 'amz_sp_api/vendor-shipments-api-model-0/models/package_item_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/packed_items'
require 'amz_sp_api/vendor-shipments-api-model-0/models/pagination'
require 'amz_sp_api/vendor-shipments-api-model-0/models/pallet'
require 'amz_sp_api/vendor-shipments-api-model-0/models/party_identification'
require 'amz_sp_api/vendor-shipments-api-model-0/models/purchase_order_items'
require 'amz_sp_api/vendor-shipments-api-model-0/models/purchase_orders'
require 'amz_sp_api/vendor-shipments-api-model-0/models/regulation_references'
require 'amz_sp_api/vendor-shipments-api-model-0/models/route'
require 'amz_sp_api/vendor-shipments-api-model-0/models/shipment'
require 'amz_sp_api/vendor-shipments-api-model-0/models/shipment_confirmation'
require 'amz_sp_api/vendor-shipments-api-model-0/models/shipment_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/shipment_information'
require 'amz_sp_api/vendor-shipments-api-model-0/models/shipment_measurements'
require 'amz_sp_api/vendor-shipments-api-model-0/models/shipment_status_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/stop'
require 'amz_sp_api/vendor-shipments-api-model-0/models/submit_shipment_confirmations_request'
require 'amz_sp_api/vendor-shipments-api-model-0/models/submit_shipment_confirmations_response'
require 'amz_sp_api/vendor-shipments-api-model-0/models/submit_shipments'
require 'amz_sp_api/vendor-shipments-api-model-0/models/tax_registration_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/total_weight'
require 'amz_sp_api/vendor-shipments-api-model-0/models/transaction_reference'
require 'amz_sp_api/vendor-shipments-api-model-0/models/transport_label'
require 'amz_sp_api/vendor-shipments-api-model-0/models/transport_shipment_measurements'
require 'amz_sp_api/vendor-shipments-api-model-0/models/transportation_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/transportation_details_for_shipment_confirmation'
require 'amz_sp_api/vendor-shipments-api-model-0/models/transportation_labels'
require 'amz_sp_api/vendor-shipments-api-model-0/models/vendor_details'
require 'amz_sp_api/vendor-shipments-api-model-0/models/volume'
require 'amz_sp_api/vendor-shipments-api-model-0/models/weight'

# APIs
require 'amz_sp_api/vendor-shipments-api-model-0/api/vendor_shipping_api'

module AmzSpApi::VendorShipmentsApiModel
  class AmzSpApi::VendorShipmentsApiModel::V0::<< self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorShipmentsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
